### ISSUE TITLE
WinAMP v2.91 (german) + in_opus.dll not showing TAGS in playlist

### ISSUE THREAD

**Issue by Benman2785** [RamonUnch/in_opus#1]
Hi,

i am 99% sure its a WinAMP error and not yours (as your Plugin shows the tags in file info)

when i have OPUS or OGG that i encode myself the tags are written in the file, windows shows them, your Plugin shows them, VLC shows them - but WinAMP v2.91 doesnt show them in playlist...

i suspect a wrong/outdated mp3tag plugin for WinAMP

how can i fix that? ;)

**Comment by RamonUnch** [comment]
> but WinAMP v2.91 doesnt show them in playlist...

Actually it is one of the limitations of the plugin, in the case of Winamp 2.x the plugin only shows the filename in the playlist.
If you use Winamp5.3+ you should have the *proper* playlist entry.

Maybe I will fix that in the future, this should not be hard to implement even on Winamp2.x, it is already the case on Winamp 5.x.

**Comment by Benman2785** [comment]
"In the Winamp playlist only the filename/URL will be visible.
  Since v0.911 proper format will be shown in the PL on Winamp 5.x"

rtfm to myself xD

i cant use WinAMP 5.x as i love AVS 2.7 - and so i am stuck with WinAMP 2.91

but thank you for your fast answer

**Comment by RamonUnch** [comment]
PS: in opus files tags are written is a specific format (same as ogg). My plugin is the only responsible for reading and showing tags and formatting the title. Proper title formatting is just much simpler on Winamp 5.x than on Winamp 2.X, this is why it is only implemented for Winamp 5.x in my plugin.

**Comment by RamonUnch** [comment]
I will have a look on how to improve title formatting for Winamp 2.x anyway.

**Comment by Benman2785** [comment]
thank you ;)

do you have a buymeacoffee or patreon? ;)

**Comment by RamonUnch** [comment]
I do not have this for now, because It is legally complex in my country, (even for a couple of cents), and I have no financial problems today. Thanks for your support though. 
I have not been in the source of this project for a couple of years, so I am not sure when I will have time to do more work on this plugin. I will also tell you if someday I create a Patreon or something.

**Comment by Benman2785** [comment]
its ok, take your time ;)

i have not found in your code how you handle tags for v5.3+ and i also dont know the specific format for tags in v2.91 - so as of now i am of no help. and my skillset is pretty small - havent really coded in 8 years.

have a good start into next week ;)

**Comment by Benman2785** [comment]
actually i figured out how to properly use my avs preset with vis_avs.dll v2.83 - this works with WinAMP v5.666 - so far it is "fixed" for me ;)

but to complete the in_opus.dll it would still be nice to add correct tags in WinAMP v2.9X

thank you for forcing me on WinAMP 5 - now everything works as i want it to ;)

**Comment by Benman2785** [comment]
happy me :)

![WinAMP_v5 666_ _vis_avs_v2 83 dll](https://user-images.githubusercontent.com/21282980/158037675-6fd64317-8c98-4923-8abe-5e09ba4cf937.jpg)

**Comment by RamonUnch** [comment]
Latest release should fix it even for Winamp 2.x:
https://github.com/RamonUnch/in_opus/releases/
Only allows "Artist - Title" formatting (default of most plugins, and also the default of Winamp 5.x)
